My Employee App/Entities/Employee.cs
namespace My_Employee_App.Entities
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }

    }
}

My Employee App/Models/AddEmployeeViewModel.cs
namespace My_Employee_App.Models
{
    public class AddEmployeeViewModel
    {
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

My Employee App/Models/EditEmployeeViewModel.cs
namespace My_Employee_App.Models
{
    public class EditEmployeeViewModel
    {
        //public int Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

My Employee App/Models/ErrorViewModel.cs
namespace My_Employee_App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

My Employee App/Models/UpdateEmployeeViewModel.cs
namespace My_Employee_App.Models
{
    public class UpdateEmployeeViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

My Employee App/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using My_Employee_App.Data;
using My_Employee_App.Entities;
using My_Employee_App.Models;

namespace My_Employee_App.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MyDbContext _dbContext;
        public EmployeesController(MyDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employees = await _dbContext.Employees.ToListAsync();
            return View(employees);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddEmployeeViewModel addEmployeeRequest)
        {
            var employee = new Employee()
            {
                Id = Guid.NewGuid(),
                Name = addEmployeeRequest.Name,
                Department = addEmployeeRequest.Department,
                Email = addEmployeeRequest.Email,
                Salary = addEmployeeRequest.Salary,
                DateOfBirth = addEmployeeRequest.DateOfBirth
            };
            await _dbContext.Employees.AddAsync(employee);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var employee = await _dbContext.Employees.FirstOrDefaultAsync(e => e.Id == id);

            if (employee != null)
            {
                var employeeModel = new UpdateEmployeeViewModel()
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    Department = employee.Department,
                    Email = employee.Email,
                    Salary = employee.Salary,
                    DateOfBirth = employee.DateOfBirth
                };
                return await Task.Run(() => View("Edit", employeeModel));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateEmployeeViewModel updateEmployeeRequest)
        {
            var employee = await _dbContext.Employees.FirstOrDefaultAsync(e => e.Id == updateEmployeeRequest.Id);
            
            if (employee != null)
            {
                employee.Name = updateEmployeeRequest.Name;
                employee.Department = updateEmployeeRequest.Department;
                employee.Email = updateEmployeeRequest.Email;
                employee.Salary = updateEmployeeRequest.Salary;
                employee.DateOfBirth = updateEmployeeRequest.DateOfBirth;
                await _dbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var employee = await _dbContext.Employees.FirstOrDefaultAsync(e => e.Id == id);
            if (employee != null)
            {
                _dbContext.Employees.Remove(employee);
                await _dbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

My Employee App/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using My_Employee_App.Models;
using System.Diagnostics;

namespace My_Employee_App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

My Employee App/Views/Employees/Create.cshtml
@model My_Employee_App.Models.AddEmployeeViewModel
@{
}

<h1>Add Employee</h1>
<form method="post" action="Create">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

My Employee App/Views/Employees/Edit.cshtml
@model My_Employee_App.Models.UpdateEmployeeViewModel
@{
}

<h1>Edit Employee</h1>
<form method="post" action="Edit">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="submit" class="btn btn-danger"
            asp-action="Delete" asp-controller="Employees">
        Delete
    </button>
</form>

My Employee App/Views/Employees/Index.cshtml
@model List<My_Employee_App.Entities.Employee>

@{
}

<h1>Employees</h1>
<li class="btn btn-link">
    <a class="btn btn-secondary" asp-area="" asp-controller="Employees" asp-action="Create">Add Employee</a>
</li>


<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Salary
            </th>
            <th>
                Date of Birth
            </th>
            <th>
                Department
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var employee in Model)
        {
            <tr>
                <td>
                    @employee.Name
                </td>
                <td>
                    @employee.Email
                </td>
                <td>
                    @employee.Salary
                </td>
                <td>
                    @employee.DateOfBirth
                </td>
                <td>
                    @employee.Department
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@employee.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@employee.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

My Employee App/Views/Employees/View.cshtml
@model My_Employee_App.Models.UpdateEmployeeViewModel
@{
}

<h1>Edit Employee</h1>
<form method="post" action="View">
        <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly >
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

My Employee App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

My Employee App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Employee App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/My_Employee_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My_Employee_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - My_Employee_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>